<?php
/**
 * Download Report API
 * Endpoint: GET /download_report.php?patient_id=X
 * Outputs a formatted PDF report as an attachment.
 */

require_once 'db_config.php';
require_once 'fpdf.php';

header_remove('Content-Type');

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    die("Method not allowed");
}

$patientId = isset($_GET['patient_id']) ? intval($_GET['patient_id']) : 0;

if ($patientId <= 0) {
    die("Invalid Patient ID");
}

try {
    $conn = getConnection();
    
    $stmt = $conn->prepare("
        SELECT p.*, pr.severity, pr.risk_score, pr.outcome, pr.notes, l.platelet_count, l.wbc_count, l.hematocrit, l.fever_days 
        FROM patients p 
        LEFT JOIN predictions pr ON p.id = pr.patient_id 
        LEFT JOIN lab_reports l ON p.id = l.patient_id 
        WHERE p.id = ? ORDER BY pr.id DESC LIMIT 1
    ");
    $stmt->execute([$patientId]);
    $data = $stmt->fetch();
    
    if (!$data) {
        die("Report not found");
    }

    $pdf = new FPDF();
    $pdf->AddPage();
    
    // Header
    $pdf->SetFont('Arial','B',20);
    $pdf->Cell(190,10,'DENGUE SEVERITY REPORT',0,1,'C');
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(190,5,'Generated by DenguePredict AI System',0,1,'C');
    $pdf->Ln(10);
    
    // Patient Details
    $pdf->SetFont('Arial','B',14);
    $pdf->SetFillColor(230,230,230);
    $pdf->Cell(190,8,' PATIENT INFORMATION',0,1,'L',true);
    $pdf->Ln(2);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(40,8,'Name:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(60,8,$data['name'],0,0);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(40,8,'Date generated:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(50,8,date('Y-m-d H:i:s'),0,1);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(40,8,'Age / Gender:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(60,8,$data['age'] . ' Y / ' . ucfirst($data['gender']),0,0);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(40,8,'Blood Group:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(50,8,$data['blood_group'],0,1);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(40,8,'Phone:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(60,8,$data['phone'],0,1);
    $pdf->Ln(5);
    
    // Lab Results
    $pdf->SetFont('Arial','B',14);
    $pdf->Cell(190,8,' LABORATORY RESULTS',0,1,'L',true);
    $pdf->Ln(2);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(45,8,'Platelet Count:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(50,8,number_format($data['platelet_count']) . ' /uL',0,0);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(45,8,'WBC Count:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(50,8,number_format($data['wbc_count']) . ' /uL',0,1);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(45,8,'Hematocrit:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(50,8,$data['hematocrit'] . '%',0,0);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(45,8,'Fever Days:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(50,8,$data['fever_days'] . ' days',0,1);
    $pdf->Ln(5);
    
    // AI Prediction
    $pdf->SetFont('Arial','B',14);
    $pdf->Cell(190,8,' AI PREDICTION RESULTS',0,1,'L',true);
    $pdf->Ln(2);
    
    $pdf->SetFont('Arial','B',12);
    $pdf->Cell(40,10,'Severity Level:',0,0);
    
    $severityColor = [0,0,0];
    if($data['severity'] == 'severe') $severityColor = [220,38,38];
    elseif($data['severity'] == 'moderate') $severityColor = [202,138,4];
    else $severityColor = [22,163,74];
    
    $pdf->SetTextColor($severityColor[0], $severityColor[1], $severityColor[2]);
    $pdf->Cell(60,10,strtoupper($data['severity']),0,1);
    $pdf->SetTextColor(0,0,0);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(40,10,'Risk Score:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(60,10,$data['risk_score'] . ' / 100',0,1);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(40,10,'Outcome:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->Cell(150,10,$data['outcome'],0,1);
    
    $pdf->SetFont('Arial','B',10);
    $pdf->Cell(40,10,'Notes:',0,0);
    $pdf->SetFont('Arial','',10);
    $pdf->MultiCell(150,10,$data['notes']);
    
    // Output
    $filename = "DengueReport_P" . str_pad($data['id'], 3, '0', STR_PAD_LEFT) . "_" . date('Ymd') . ".pdf";
    $pdf->Output('D', $filename);
    
} catch (PDOException $e) {
    die("Database error: " . $e->getMessage());
} catch (Exception $e) {
    die("General error: " . $e->getMessage());
}
?>
