<?php
/**
 * Share Report API
 * Endpoint: GET /share_report.php?patient_id=X
 * Generates a clean text string summarizing the diagnosis for sharing.
 */

require_once 'db_config.php';

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    sendResponse(false, 'Method not allowed', [], 405);
}

$patientId = isset($_GET['patient_id']) ? intval($_GET['patient_id']) : 0;

if ($patientId <= 0) {
    sendResponse(false, 'Invalid patient ID', [], 400);
}

try {
    $conn = getConnection();
    
    // Get summary details
    $stmt = $conn->prepare("
        SELECT p.name, pr.severity, pr.risk_score 
        FROM patients p 
        LEFT JOIN predictions pr ON p.id = pr.patient_id 
        WHERE p.id = ? ORDER BY pr.id DESC LIMIT 1
    ");
    $stmt->execute([$patientId]);
    $data = $stmt->fetch();
    
    if (!$data) {
        sendResponse(false, 'Patient not found', [], 404);
    }
    
    $shareText = "DenguePredict Risk Assessment:\n"
               . "Patient: " . $data['name'] . "\n"
               . "Severity: " . ucfirst($data['severity']) . "\n"
               . "Risk Score: " . $data['risk_score'] . "/100\n\n"
               . "Generated by DenguePredict AI system.";
               
    sendResponse(true, 'Share text generated', ['share_text' => $shareText]);
    
} catch (PDOException $e) {
    sendResponse(false, 'Error generating share summary', [], 500);
}
?>
